server.port=8083
spring.application.name=chatbot-service

# MongoDB local (Docker)
spring.data.mongodb.uri=mongodb://localhost:27017/db_chatbot

# JWT
jwt.secret=kidcare-secret-key-2024-segura-32chars
jwt.expiration=86400000
